


//PRODUCT ACTIONS TYPES

export const GET_APARTMENT_CITYS_LIST = 'GET_APARTMENT_CITYS_LIST';
export const GET_PRODUCTS_WOOD_LIST ='GET_PRODUCTS_WOOD_LIST';
export const GET_APARTMENT_LISTS = 'GET_APARTMENT__LISTS'
export const ADD_WOODS = 'ADD_WOODS'
export const GET_APARTMENTS_DETAIL='GET_APARTMENTS_DETAIL'
export const CLEAR_APARTMENT_DETAIL ='CLEAR_APARTMENTS_DETAIL'
export const ADD_TO_CART = 'ADD_TO_CART'
